service: lambdaborghini

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: version-1


custom:
  region: ${opt:region, self:provider.region}
  myStage: ${opt:stage, self:provider.stage}
  base: ${self:service}-${self:custom.myStage}
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules: true
#  serverless-layers:
#    - common:
#        dependenciesPath: ./package.json
#        layersDeploymentBucket: ${self:custom.base}-layers

plugins:
#  - serverless-layers
  - serverless-webpack
  - serverless-iam-roles-per-function

functions:
  cpu-intencive:
    handler: src/functions/cpu-intencive.handler
    iamRoleStatements:
      - Effect: Allow
        Action: ssm:GetParameter
        Resource: arn:aws:ssm:*
