service: lambdaborghini

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

functions:
  write-batch:
    handler: src/functions/write-batch.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:*"
        Resource: !GetAtt UsersTable.Arn
      - Effect: Allow
        Action: ssm:GetParameter
        Resource: arn:aws:ssm:*
  do-appsync:
    handler: src/functions/do-appsync.handler


resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.base}-users
